/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-12-02 10:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jailer_005fmanage_002dyz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/prison/plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css\"/>\n");
      out.write("\t\t<title>狱警管理</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/prison/css/warden-yz.css\"/>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("    <!-- 导航 -->\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-inverse\" role=\"navigation\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <span class=\"navbar-brand\">好再来监狱</span>\n");
      out.write("            <small class=\"navbar-text\">一个充满人文关怀的监狱</small>\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("          <ul class=\"nav navbar-nav\">\n");
      out.write("            <li>\n");
      out.write("              <a href=\"warden_home-yz.jsp\">监狱管理</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"active\">\n");
      out.write("              <a href=\"#\">狱警管理</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"prisoner_manage-yz.jsp\">囚犯管理</a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("    <!-- 导航结束 -->\n");
      out.write("    \n");
      out.write("    <div class=\"outer\">\n");
      out.write("     <div class=\"my-left-nav\">\n");
      out.write("        <ul class=\"nav nav-pills nav-stacked nav-left\">\n");
      out.write("          <li role=\"presentation\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-default btn-lg btn-block my-left-nav-btn\" onclick=\"location.href='#'\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">狱警一览</a>\n");
      out.write("            </button>\n");
      out.write("          </li>\n");
      out.write("          <li role=\"presentation\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-default btn-lg btn-block my-left-nav-btn\" onclick=\"location.href='#'\">\n");
      out.write("              <a href=\"#\">工作分配</a>\n");
      out.write("            </button>\n");
      out.write("          </li>\n");
      out.write("          <li role=\"presentation\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-default btn-lg btn-block my-left-nav-btn\" onclick=\"location.href='#'\">\n");
      out.write("              <a href=\"#\">出勤统计</a>\n");
      out.write("            </button>\n");
      out.write("          </li>\n");
      out.write("          <li role=\"presentation\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-default btn-lg btn-block my-left-nav-btn\" onclick=\"location.href='#'\">\n");
      out.write("              <a href=\"#\">薪金奖励</a>\n");
      out.write("            </button>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <!-- my-left-nav结束 -->\n");
      out.write("      \n");
      out.write("      <div class=\"my-body\">\n");
      out.write("      \t<h1>好再来监狱<small>——狱警一览</small></h1>\n");
      out.write("        <hr>\n");
      out.write("\n");
      out.write("        <table class=\"table my-table-hover my-table\" border=\"1\" cellspacing=\"5\" cellpadding=\"5\">\r\n");
      out.write("        \t<caption><h3>狱警列表</h3></caption>\r\n");
      out.write("        \t<thead>\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<th>狱警编号</th>\r\n");
      out.write("        \t\t\t<th>狱警姓名</th>\r\n");
      out.write("        \t\t\t<th>管理区域</th>\r\n");
      out.write("        \t\t\t<th>月薪（元）</th>\r\n");
      out.write("        \t\t\t<th>行为评分</th>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t</thead>\r\n");
      out.write("        \t<tbody>\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td>145219</td>\r\n");
      out.write("        \t\t\t<td>Mr Huang</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>C</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>3400</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>15</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td>145319</td>\r\n");
      out.write("        \t\t\t<td>Mr Huang</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>C</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>3400</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>12</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td>145119</td>\r\n");
      out.write("        \t\t\t<td>Mr Huang</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>E</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>3400</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>3</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td>145249</td>\r\n");
      out.write("        \t\t\t<td>Mr Huang</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>A</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>3400</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t</tbody>\r\n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <!-- my-body结束 -->\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("    <!-- outer结束 -->\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- 引入jquery -->\n");
      out.write("\t\t<script src=\"/prison/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("\t\t<!-- 引入bootstrap.min.js -->\n");
      out.write("\t\t<script src=\"/prison/plugins/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
